TYPE_TEST = 'test'
TYPE_DATA = 'data'

TYPE = "type"

VERSION_1 = 1.0
VERSION_KEY = 'version'

VERSION_SUPPORTED = ['1.0']

DATA_KEY_NAME = "name"
DATA_KEY_SCHEMA = "schema"
DATA_KEY_VALUES = "values"
DATA_KEY_VALUES_ROW = "row"
DATE_KEY_OUTPUT_FORMATING = "output_formating"

TEST_KEY_PRELOAD = "preload"
TEST_KEY_SQL = "sql"
TEST_KEY_NAME = "name"
TEST_KEY_TABLES = "tables"
TEST_KEY_TESTCASES = "testcases"
TEST_KEY_TESTCASE = "testcase"
TEST_KEY_TESTCASE_NAME = "name"
TEST_KEY_TESTCASE_INPUT = "input"
TEST_KEY_TESTCASE_INPUT_DATA = "data"
TEST_KEY_TESTCASE_INPUT_DATA_PATH = "data_path"
TEST_KEY_TESTCASE_OUTPUT = "output"
TEST_KEY_TESTCASE_OUTPUT_SCHEMA = "schema"
TEST_KEY_TESTCASE_OUTPUT_VALUES = "values"
TEST_KEY_TESTCASE_OUTPUT_VALUES_ROW = "row"

TYPE_SUPPORTED = [
  TYPE_TEST,
  TYPE_DATA
]

DATA_KEYS = [
  # VERSION_KEY,
  DATA_KEY_NAME,
  DATA_KEY_SCHEMA,
  DATA_KEY_VALUES
]

TEST_KEYS_MUST = [
  # VERSION_KEY,
  TEST_KEY_SQL,
  TEST_KEY_NAME,
  TEST_KEY_TABLES,
  TEST_KEY_TESTCASES
]

TEST_KEYS_TESTCASE_MUST = [
  TEST_KEY_TESTCASE_NAME,
  TEST_KEY_TESTCASE_INPUT,
  TEST_KEY_TESTCASE_OUTPUT
]

TEST_KEYS_TESTCASE_OUTPUT_MUST = [
  TEST_KEY_TESTCASE_OUTPUT_SCHEMA,
  TEST_KEY_TESTCASE_OUTPUT_VALUES
]